import React from "react";

import { Icomponent } from "../../../core/components/basegame/interface/Icomponent";
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";


interface IframeworkNoInternetPopUp {
    data: {
        COMPONENTS: Icomponent[]
    }

}

export const frameworkNoInternetPopUp: IframeworkNoInternetPopUp = {

    data: {
        "COMPONENTS": [
            {
                "id": "noInternetPopUpContainerDesktop",
                "name": "noInternetPopUpContainerDesktop",
                "type": "Container",
                "class": "",
                "x": 0,
                "y": 0,
                "uimode": "desktop",
                "layout": false,
                "filterTypes": [],
                child: [
                    {
                        "id": "graphic_1",
                        "name": "graphic_1",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0x000000",
                        "alpha": 0.89,
                        "x": 55,
                        "y": 456,
                        "width": 1800,
                        "height": 250,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "graphic_2",
                        "name": "graphic_2",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 97,
                        "y": 534,
                        "width": 1700,
                        "height": 2,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "graphic_3",
                        "name": "graphic_3",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 97,
                        "y": 619,
                        "width": 1700,
                        "height": 2,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "noInternetPopUpText1",
                        "name": "noInternetPopUpText1",
                        "type": "Text",
                        "x": 955,
                        "y": 500,
                        "width": 250,
                        "height": 300,
                        "text": "noInternetPopUpText1",
                        "scaleToFit": true,
                        "visible": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 40,
                            fontWeight: 'bold',
                            fill: ['#f8f8ff'],
                        },
                    },
                    {
                        "id": "noInternetPopUpText2",
                        "name": "noInternetPopUpText2",
                        "type": "Text",
                        "x": 1000,
                        "y": 577,
                        "width": 1000,
                        "height": 300,
                        "text": "noInternetPopUpText2",
                        "scaleToFit": true,
                        "visible": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 200,
                            fontWeight: 'bold',
                            fill: ['#f8f8ff'],
                        },
                    },

                    {
                        "id": "closeButtonPopUp",
                        "name": "closeButtonPopUp",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "x": 636,
                        "y": 633,
                        "width": 226,
                        "height": 65,
                        "text": "",
                        "visible": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },
                    {
                        "id": "closeButtonPopUp_text",
                        "name": "closeButtonPopUp_text",
                        "type": "Text",
                        "x": 755,
                        "y": 665,
                        "width": 180,
                        "visible": true,
                        "text": "realityCheckText7",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },

                    {
                        "id": "continueButtonPopUp",
                        "name": "continueButtonPopUp",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "x": 1040,
                        "y": 633,
                        "width": 226,
                        "height": 65,
                        "text": "",
                        "visible": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },
                    {
                        "id": "continueButtonPopUp_text",
                        "name": "continueButtonPopUp_text",
                        "type": "Text",
                        "x": 1155,
                        "y": 665,
                        "width": 180,
                        "visible": true,
                        "text": "realityCheckText6",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },
                ]
            },

            {
                "id": "noInternetPopUpContainerMobile",
                "name": "noInternetPopUpContainerMobile",
                "type": "Container",
                "class": "",
                "x": 0,
                "y": 0,
                "uimode": "mobile",
                "layout": true,
                "visible": true,
                "filterTypes": [],
                child: [
                    {
                        "id": "graphic_1",
                        "name": "graphic_1",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0x000000",
                        "alpha": 0.89,
                        "x": 55,
                        "y": 465,
                        "width": 1800,
                        "height": 255,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "graphic_2",
                        "name": "graphic_2",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 97,
                        "y": 551.5,
                        "width": 1700,
                        "height": 2,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "graphic_3",
                        "name": "graphic_3",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 97,
                        "y": 632.5,
                        "width": 1700,
                        "height": 2,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "noInternetPopUpText1",
                        "name": "noInternetPopUpText1",
                        "type": "Text",
                        "x": 955,
                        "y": 510,
                        "width": 250,
                        "height": 300,
                        "text": "noInternetPopUpText1",
                        "scaleToFit": true,
                        "visible": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 40,
                            fontWeight: 'bold',
                            fill: ['#f8f8ff'],
                        },
                    },
                    {
                        "id": "noInternetPopUpText2",
                        "name": "noInternetPopUpText2",
                        "type": "Text",
                        "x": 1000,
                        "y": 590,
                        "width": 1000,
                        "height": 300,
                        "text": "noInternetPopUpText2",
                        "scaleToFit": true,
                        "visible": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 200,
                            fontWeight: 'bold',
                            fill: ['#f8f8ff'],
                        },
                    },
                    {
                        "id": "closeButtonPopUp",
                        "name": "closeButtonPopUp",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "x": 636,
                        "y": 645,
                        "width": 226,
                        "height": 65,
                        "text": "",
                        "visible": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },
                    {
                        "id": "closeButtonPopUp_text",
                        "name": "closeButtonPopUp_text",
                        "type": "Text",
                        "x": 755,
                        "y": 676,
                        "width": 180,
                        "visible": true,
                        "text": "realityCheckText7",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },

                    {
                        "id": "continueButtonPopUp",
                        "name": "continueButtonPopUp",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "x": 1040,
                        "y": 645,
                        "width": 226,
                        "height": 65,
                        "text": "",
                        "visible": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },
                    {
                        "id": "continueButtonPopUp_text",
                        "name": "continueButtonPopUp_text",
                        "type": "Text",
                        "x": 1155,
                        "y": 676,
                        "width": 180,
                        "visible": true,
                        "text": "realityCheckText6",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },
                ]
            },
        ],
    }
};

export const NoInternetPopUpConfigurationContext = React.createContext(
    {}
);